// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt_pZiDJHy_lG3elDheyKhhW00cyieqF8',
    appId: '1:166022302292:web:fe72b852f5124adeb8fbc1',
    messagingSenderId: '166022302292',
    projectId: 'parth-prajapati-resume',
    authDomain: 'parth-prajapati-resume.firebaseapp.com',
    databaseURL: 'https://parth-prajapati-resume-default-rtdb.firebaseio.com',
    storageBucket: 'parth-prajapati-resume.firebasestorage.app',
    measurementId: 'G-Y0LCHVFE1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCDYsGwEZCDlS_5q1YbDd8xI71U0EP0gU',
    appId: '1:166022302292:android:517aa5f1a1202f74b8fbc1',
    messagingSenderId: '166022302292',
    projectId: 'parth-prajapati-resume',
    databaseURL: 'https://parth-prajapati-resume-default-rtdb.firebaseio.com',
    storageBucket: 'parth-prajapati-resume.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdHHmqbX6urhiXOthTIIHJY5BJi9Zu6K0',
    appId: '1:166022302292:ios:25abac9b1b9d6a26b8fbc1',
    messagingSenderId: '166022302292',
    projectId: 'parth-prajapati-resume',
    databaseURL: 'https://parth-prajapati-resume-default-rtdb.firebaseio.com',
    storageBucket: 'parth-prajapati-resume.firebasestorage.app',
    iosBundleId: 'com.example.myResumeApp',
  );
}
